//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiftDomain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Organization_template {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Organization_template() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiftDomain.Organization.template", typeof(Organization_template).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @pageIndex INT
        ///DECLARE @pageSize INT 
        ///
        ///SET @pageIndex = ${pageIndex}
        ///SET @pageSize = ${pageSize}
        ///
        ///WITH    usersRN
        ///          AS (
        ///SELECT  ROW_NUMBER() OVER ( ORDER BY [title] ) AS RowNum,
        ///        id,
        ///        created_at,
        ///        [title],
        ///        subdomain,
        ///        organization_id,
        ///        [address],
        ///        city,
        ///        state_province,
        ///        postal_code,
        ///        phone,
        ///        time_zone,
        ///        language_id
        ///FROM    dbo.organizations
        ///             )
        ///SELECT  *
        ///FROM    organizat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllOrganizations {
            get {
                return ResourceManager.GetString("GetAllOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM organizations WHERE title LIKE &apos;%&apos;+${search}+ &apos;%&apos; OR subdomain LIKE &apos;%&apos;+${search}+ &apos;%&apos; ORDER BY title.
        /// </summary>
        internal static string SearchOrganizationsByTitleOrSubdomain {
            get {
                return ResourceManager.GetString("SearchOrganizationsByTitleOrSubdomain", resourceCulture);
            }
        }
    }
}
