//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiftDomain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Request_template {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Request_template() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiftDomain.Request.template", typeof(Request_template).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update requests set is_approved=${is_approved}, updated_at=${updated_at}, last_action=${last_action} where id=${id}.
        /// </summary>
        internal static string approve_internal {
            get {
                return ResourceManager.GetString("approve_internal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from
        ///(
        ///select r.id, r.title, r.description, r.post_date [post_date], r.[from], r.from_email
        ///from requests r where r.id=${id}
        ///union all
        ///select r2.id, r2.title, e.note [description], e.post_date [post_date],e.[from], e.from_email
        ///from
        ///requests r2, encouragements e
        ///where e.request_id=r2.id
        ///and r2.id=${id}
        ///) x
        ///order by x.post_date desc.
        /// </summary>
        internal static string get_most_recent_update {
            get {
                return ResourceManager.GetString("get_most_recent_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *, isnull( rt.title, &apos;&apos;) [requesttype_title] FROM requests r 
        ///LEFT OUTER JOIN requesttypes rt ON rt.id = r.requesttype_id
        ///WHERE r.organization_id=${organization_id}
        ///AND (r.user_id=${user_id}) 
        ///	.
        /// </summary>
        internal static string get_my_account_requests {
            get {
                return ResourceManager.GetString("get_my_account_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *, isnull( rt.title, &apos;&apos;) [requesttype_title] FROM requests r 
        ///left outer join requesttypes rt on rt.id = r.requesttype_id
        ///WHERE r.organization_id=${organization_id}
        ///AND (r.id=${id}) 
        ///	.
        /// </summary>
        internal static string get_request {
            get {
                return ResourceManager.GetString("get_request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to declare @approval_threshold int
        ///declare @listed_threshold int
        ///declare @timeframe int
        ///declare @organization_id int
        ///declare @requesttype int
        ///declare @search varchar(100)
        ///declare @active int
        ///
        ///set @approval_threshold=${approval_threshold}
        ///set @listed_threshold=${listed_threshold}
        ///set @timeframe=${timeframe}
        ///set @organization_id=${organization_id}
        ///set @requesttype=${requesttype}
        ///set @search=${search}
        ///set @active=${active}
        ///
        ///SELECT r.*, 
        ///isnull( rt.title, &apos;&apos;) [requesttype_title], 
        ///isnull( enc_req [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string get_requests {
            get {
                return ResourceManager.GetString("get_requests", resourceCulture);
            }
        }
    }
}
