//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiftDomain {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class User_template {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal User_template() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiftDomain.User.template", typeof(User_template).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @email NVARCHAR(200)
        ///DECLARE @pageIndex INT
        ///DECLARE @pageSize INT 
        ///
        ///SET @email = ${email}
        ///SET @pageIndex = ${pageIndex}
        ///SET @pageSize = ${pageSize}
        ///
        ///WITH    usersRN
        ///          AS ( SELECT   ROW_NUMBER() OVER ( ORDER BY [login] ) AS RowNum,
        ///                        id,
        ///                        created_at,
        ///                        updated_at,
        ///                        last_logged_in_at,
        ///                        login_failure_count,
        ///                        [login],
        ///                        emai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FindUsersByEmail {
            get {
                return ResourceManager.GetString("FindUsersByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @login NVARCHAR(100)
        ///DECLARE @pageIndex INT
        ///DECLARE @pageSize INT 
        ///
        ///SET @login = ${login}
        ///SET @pageIndex = ${pageIndex}
        ///SET @pageSize = ${pageSize}
        ///
        ///WITH    usersRN
        ///          AS ( SELECT   ROW_NUMBER() OVER ( ORDER BY [login] ) AS RowNum,
        ///                        id,
        ///                        created_at,
        ///                        updated_at,
        ///                        last_logged_in_at,
        ///                        login_failure_count,
        ///                        [login],
        ///                        emai [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FindUsersByName {
            get {
                return ResourceManager.GetString("FindUsersByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select id [user_id], first_name, last_name from users u where u.first_name like &apos;%&apos; + ${q} + &apos;%&apos; or u.last_name like &apos;%&apos;+${q}+&apos;%&apos; and len(${q}) &gt;=3 and u.organization_id=${organization_id}.
        /// </summary>
        internal static string get_users_like {
            get {
                return ResourceManager.GetString("get_users_like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @pageIndex INT
        ///DECLARE @pageSize INT 
        ///
        ///SET @pageIndex = ${pageIndex}
        ///SET @pageSize = ${pageSize}
        ///
        ///WITH    usersRN
        ///          AS (
        ///SELECT  ROW_NUMBER() OVER ( ORDER BY [login] ) AS RowNum,
        ///        id,
        ///        created_at,
        ///        updated_at,
        ///        last_logged_in_at,
        ///        login_failure_count,
        ///        [login],
        ///        email,
        ///        crypted_password,
        ///        password_hash_type,
        ///        password_salt,
        ///        [state],
        ///        first_name,
        ///        last_name,
        ///        organization_i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllUsers {
            get {
                return ResourceManager.GetString("GetAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @lastLogin DATETIME
        ///SET @lastLogin = ${last_logged_in_at}
        ///
        ///SELECT  COUNT(*)
        ///FROM    [dbo].[users]
        ///WHERE   [last_logged_in_at] &gt; @lastLogin.
        /// </summary>
        internal static string GetNumberOfUsersOnline {
            get {
                return ResourceManager.GetString("GetNumberOfUsersOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM users WHERE organization_id = ${organization_id} and state = 2  .
        /// </summary>
        internal static string SearchConfirmedUsersByOrg {
            get {
                return ResourceManager.GetString("SearchConfirmedUsersByOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [login] [username], * FROM users WHERE email = ${search}.
        /// </summary>
        internal static string SearchUsersByEmail {
            get {
                return ResourceManager.GetString("SearchUsersByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM users 
        ///WHERE ( first_name LIKE &apos;%&apos;+${search}+ &apos;%&apos; 
        ///OR last_name LIKE &apos;%&apos;+${search}+ &apos;%&apos; 
        ///OR email LIKE &apos;%&apos;+${search}+ &apos;%&apos;) and
        ///(${state} = 0 or (state=${state}))
        /// and organization_id=${organization_id} ORDER BY last_name, first_name.
        /// </summary>
        internal static string SearchUsersByFirstOrLast {
            get {
                return ResourceManager.GetString("SearchUsersByFirstOrLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT u.*, o.title as org_title
        /// FROM users u,
        ///organizations o
        /// WHERE (u.first_name LIKE &apos;%&apos;+${search}+ &apos;%&apos; 
        ///OR u.last_name LIKE &apos;%&apos;+${search}+ &apos;%&apos; 
        ///OR u.email LIKE &apos;%&apos;+${search}+ &apos;%&apos; ) and
        ///(${state} = 0 or (state=${state}))
        ///and o.id=u.organization_id
        ///ORDER BY u.last_name, u.first_name.
        /// </summary>
        internal static string SearchUsersByFirstOrLastSysAdmin {
            get {
                return ResourceManager.GetString("SearchUsersByFirstOrLastSysAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM users WHERE organization_id = ${search}.
        /// </summary>
        internal static string SearchUsersByOrg {
            get {
                return ResourceManager.GetString("SearchUsersByOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [login] [username], * FROM users WHERE [login] = ${search}.
        /// </summary>
        internal static string SearchUsersByUsername {
            get {
                return ResourceManager.GetString("SearchUsersByUsername", resourceCulture);
            }
        }
    }
}
